version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/docker" # Adjust if your Dockerfile is in a subdirectory
    schedule:
      interval: "weekly"
