name: LDIF Syntax Check

# Run this workflow on pushes and pull requests to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-ldif-syntax:
    name: Check LDIF Syntax
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Install the necessary LDAP command-line tools
      - name: Install ldap-utils
        run: |
          sudo apt-get update
          sudo apt-get install -y ldap-utils

      # Step 3: Find all .ldif files and validate them
      - name: Validate all LDIF files
        run: |
          find . -type f -name "*.ldif" | while read -r file; do
            echo "--> Checking syntax of ${file}"
            # Use ldapadd's dry-run mode (-n) to check syntax without connecting to a server
            ldapadd -n -f "${file}"
          dones